#!/bin/bash

INNAME=$1
OUTNAME=$2

# Remake output if not there.
if [ -e ${OUTNAME} ]; then
		REMAKE=0
else
		REMAKE=1
fi

# if we are newer...
test ${0} -nt ${OUTNAME} && REMAKE=1

# if ghostscriptifyPDF is newer...
test ghostscriptifyPDF -nt ${OUTNAME} && REMAKE=1

# if input is newer...
test $(readlink -f ${INNAME}) -nt ${OUTNAME} && REMAKE=1

if [ ${REMAKE} -eq 1 ]; then
		echo "Need to remake ${OUTNAME}..."
		# Remove output so LaTeX will never pickup old stuff no matter our exit status.
		rm ${OUTNAME}
else
		echo "${OUTNAME} still current."
		exit 0
fi

inkscape --version | grep -q 'Inkscape 1'
if [ $? -eq 0 ]; then
		# New version of Inkscape, overhauled CLI.
		inkscape -D --export-filename="$(pwd)/${OUTNAME}" --export-pdf-version=1.4 "$(pwd)/${INNAME}"
else
		inkscape -D -z --file="$(pwd)/${INNAME}" --export-pdf="$(pwd)/${OUTNAME}"
fi

if [ $? -eq 0 ]; then
		echo "Remaking ${OUTNAME} went well."
		./ghostscriptifyPDF ${OUTNAME}
else
		echo "Remaking of ${OUTNAME} failed, removing it!"
		rm ${OUTNAME}
fi
