#!/bin/bash

INNAME=$1
OUTNAME=$2

# Remake output if not there.
if [ -e ${OUTNAME} ]; then
		REMAKE=0
else
		REMAKE=1
fi

# if we are newer...
test ${0} -nt ${OUTNAME} && REMAKE=1

# if input is newer...
test ${INNAME} -nt ${OUTNAME} && REMAKE=1

if [ ${REMAKE} -eq 1 ]; then
		echo "Need to remake ${OUTNAME}..."
		# Remove output so LaTeX will never pickup old stuff no matter our exit status.
		rm ${OUTNAME}
else
		echo "${OUTNAME} still current."
		exit 0
fi

inkscape -D -z --file="${INNAME}" --export-pdf="${OUTNAME}"
