#!/bin/bash
DIM=${1:-1200x800}

#while true; do
#	PLOTFILE=$(inotifywait -q -e close_write plots/*.C | awk '{print $1}')
#	./makeRootPlot ${PLOTFILE%.C}_${DIM}.{C,pdf}
#	PIDOFZATHURA=$(pgrep -f -x 'zathura '${PLOTFILE%.C}_${DIM}.pdf)
#	test -z ${PIDOFZATHURA} && zathura ${PLOTFILE%.C}_${DIM}.pdf &
#done

inotifywait -m -q --format %w%f -e close_write plots | while read PLOTFILE; do
	if [[ "${PLOTFILE}" != *.C ]]; then
		continue;
	fi
	./makeRootPlot ${PLOTFILE%.C}_${DIM}.{C,pdf}
	if [[ $? -eq 0 ]]; then
		PIDOFZATHURA=$(pgrep -f -x 'zathura '${PLOTFILE%.C}_${DIM}.pdf)
		test -z ${PIDOFZATHURA} || continue
		echo "Start new zathura instance..."
		zathura ${PLOTFILE%.C}_${DIM}.pdf &
	fi
	#echo $PIDOFZATHURA
	#echo ${PLOTFILE%.C}_${DIM}.pdf
	#sleep 1
done
