#!/bin/bash
DIM=${1:-1200x800}

PLOTDIR=plots

inotifywait -m -q --format %w%f -e close_write ${PLOTDIR} ${PLOTDIR}/*/ | while read PLOTFILE; do
	if [[  $(grep -o "/" "${PLOTFILE}" | wc -l) -gt 1 ]]; then
		STRIPPED_INCLUDE=${PLOTFILE#${PLOTDIR}/}
		echo "Include file ${STRIPPED_INCLUDE} changed!"
		for AFFECTED_FILE in $(grep -l ${STRIPPED_INCLUDE} ${PLOTDIR}/*.C); do
			echo "... affects: ${AFFECTED_FILE}!"
			touch ${AFFECTED_FILE}
		done
	fi
	if [[ "${PLOTFILE}" != *.C ]]; then
		continue;
	fi
	echo "Plotfile ${PLOTFILE} changed!"
	./makeRootPlot ${PLOTFILE%.C}_${DIM}.{C,pdf} && \
	(
		echo "Plotfile ${PLOTFILE} remade successfully."
		PIDOFZATHURA=$(pgrep -f -x 'zathura '${PLOTFILE%.C}_${DIM}.pdf)
		test -z ${PIDOFZATHURA} || continue
		echo "Start new zathura instance..."
		zathura ${PLOTFILE%.C}_${DIM}.pdf &
	) &
done
